### ISSUE TITLE
Can't use this project

### ISSUE THREAD

**Issue by montogeek** [glennsl/bs-json#38] opened 2018-05-24 11:16 UTC
Hi Glenn,

I am sorry to open this issue, it is more an issue with how BuckleScript works.
After installing your project using `npm install --save @glennsl/bs-json` and then added it to `bsconfig.json` under `bs-dependencies` I get this error when running `bsb -make-world` in the root of my project:
```bash
👉  bsb -make-world
ninja: no work to do.
Duplicated package: bs-platform /Users/montogeek/Infinite/Lov/online/node_modules/bs-platform (chosen) vs /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/node_modules/bs-platform in /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json
[1/3] Building src/Json_encode.cmj
FAILED: src/Json_encode.cmj /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/src/Json_encode.bs.js
/Users/montogeek/.nvm/versions/node/v10.0.0/lib/node_modules/bs-platform/lib/bsc.exe -bs-package-name @glennsl/bs-json  -bs-package-output commonjs:src -bs-assume-has-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include   -I src  -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I '/Users/montogeek/Infinite/Lov/online/node_modules/bs-platform/lib/ocaml' -bs-no-version-header -bs-super-errors -no-alias-deps -color always -o src/Json_encode.cmj -c  src/Json_encode.mlast
Fatal error: exception Failure("File \"external_ffi_types.ml\", line 261, characters 13-20Compiler version mismatch. The project might have been built with one version of BuckleScript, and then with another. Please wipe the artifacts and do a clean build.")
[2/3] Building src/Json_decode.cmj
FAILED: src/Json_decode.cmj /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/src/Json_decode.bs.js
/Users/montogeek/.nvm/versions/node/v10.0.0/lib/node_modules/bs-platform/lib/bsc.exe -bs-package-name @glennsl/bs-json  -bs-package-output commonjs:src -bs-assume-has-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include   -I src  -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I '/Users/montogeek/Infinite/Lov/online/node_modules/bs-platform/lib/ocaml' -bs-no-version-header -bs-super-errors -no-alias-deps -color always -o src/Json_decode.cmj -c  src/Json_decode.mlast
Fatal error: exception Failure("File \"external_ffi_types.ml\", line 261, characters 13-20Compiler version mismatch. The project might have been built with one version of BuckleScript, and then with another. Please wipe the artifacts and do a clean build.")
ninja: build stopped: subcommand failed.
Failure: /Users/montogeek/.nvm/versions/node/v10.0.0/lib/node_modules/bs-platform/lib/ninja.exe
 Location: /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/lib/bs
```

I already tried installing dependencies in your project then run `bsb -make-world` but get the same error:
```bash
montogeek ~/Infinite/Lov/online/node_modules/@glennsl/bs-json [01:12 PM]→ 😀  (master)
👉  bsb -make-world
[1/1] Building src/jest.cmj
FAILED: src/jest.cmj /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/node_modules/bs-jest/src/jest.js
/Users/montogeek/.nvm/versions/node/v10.0.0/lib/node_modules/bs-platform/lib/bsc.exe -bs-package-name bs-jest  -bs-package-output commonjs:src -bs-assume-has-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include   -I src  -w -30-40+6+7+27+32..39+44+45+101 -nostdlib -I '/Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/node_modules/bs-platform/lib/ocaml' -bs-no-version-header -bs-super-errors -no-alias-deps -color always -o src/jest.cmj -c  src/jest.mlast

  Warning number 3
  /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/node_modules/bs-jest/src/jest.ml 86:66-86

  84 ┆ | Equal `Just (a, b) -> (expect a) ## toEqual b
  85 ┆ | Equal `Not (a, b) -> (expect a) ## not ## toEqual b
  86 ┆ | FloatCloseTo `Just (a, b, p) -> (expect a) ## toBeCloseTo b (Js.Unde
       fined.from_opt p)
  87 ┆ | FloatCloseTo `Not (a, b, p) -> (expect a) ## not ## toBeCloseTo b (J
       s.Undefined.from_opt p)
  88 ┆ | GreaterThan `Just (a, b) -> (expect a) ## toBeGreaterThan b

  deprecated: Js.Undefined.from_opt
Use fromOption instead

  Warning number 3
  /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/node_modules/bs-jest/src/jest.ml 87:72-92

  85 ┆ | Equal `Not (a, b) -> (expect a) ## not ## toEqual b
  86 ┆ | FloatCloseTo `Just (a, b, p) -> (expect a) ## toBeCloseTo b (Js.Unde
       fined.from_opt p)
  87 ┆ | FloatCloseTo `Not (a, b, p) -> (expect a) ## not ## toBeCloseTo b (J
       s.Undefined.from_opt p)
  88 ┆ | GreaterThan `Just (a, b) -> (expect a) ## toBeGreaterThan b
  89 ┆ | GreaterThan `Not (a, b) -> (expect a) ## not ## toBeGreaterThan b

  deprecated: Js.Undefined.from_opt
Use fromOption instead
Fatal error: exception Failure("File \"external_ffi_types.ml\", line 261, characters 13-20Compiler version mismatch. The project might have been built with one version of BuckleScript, and then with another. Please wipe the artifacts and do a clean build.")
ninja: build stopped: subcommand failed.
Failure: /Users/montogeek/.nvm/versions/node/v10.0.0/lib/node_modules/bs-platform/lib/ninja.exe
 Location: /Users/montogeek/Infinite/Lov/online/node_modules/@glennsl/bs-json/node_modules/bs-jest/lib/bs
```

BuckleScript isn't really been helpful (https://github.com/BuckleScript/bucklescript/pull/2347).

Additional info:
```bash
montogeek ~/Infinite/Lov/online [01:17 PM]→ 😀  (master)
👉  bsb -version
3.1.1
```
```json
  "devDependencies": {
    "bs-platform": "3.1.3",
    "bs-fetch": "0.3.0"
  }
```

Thanks for help a new comer.

**Comment by glennsl** [comment] 2018-05-24 12:21
Hi. I've seen this a few times before, but I'm not entirely sure what the root cause of it is. I don't think it's an issue with `bs-json` itself though.

It might be because there's a mismatch between the version you have installed globally and the one you have locally (in your project or in either of the dependencies). Unless you have `npm link`ed it in, you should avoid using the global `bsb` to build the project. You can use `npx bsb -make-world` instead, which will use the local dependency, or set up a proper npm script (most templates and boilerplate will have done this for you).

It might also be because you've built it previously with a different version of the compiler. If so, and really any time you have build issues, you should run `bsb -clean-world` to clean up old build artifacts.

I'll close this since I don't think there's anything to "fix" on the library-side here, and would recommend you to bring issues like this to the Discord, where you'll reach a lot more people and get much quicker and better help than I can provide here. Let me know if there does turn out to be something that can be fixed in the library though.

Hope this helps :)

**Closed by glennsl** 2018-05-24 12:21 UTC
