### ISSUE TITLE
Support for int64

### ISSUE THREAD

**Issue by ChristophGr** [glennsl/bs-json#39] opened 2018-06-06 04:23 UTC
I tried with a custom decoder function, but it did not work as it is passed an already parsed number as double, so values >2^53 are rounded.

**Comment by glennsl** [comment] 2018-06-06 11:52
Hey. Can you give an example to reproduce the issue?

**Comment by ChristophGr** [comment] 2018-06-06 15:30
let jsonString = "{ \"number\": 9007199254740993 }";

    type parsed = {
      number: int,
    };

    let decode = json => Json.Decode.(
      {
        number: json |> field("number", int)
      }
    );

outputs

    {number: 9007199254740992}

So what I would like to do:

    type parsed = {
      number: int64,
    };

    let decode = json => Json.Decode.(
      {
        number: json |> field("number", int64)
      }
    );

**Comment by glennsl** [comment] 2018-06-06 15:59
Right, that's unfortunately a fundamental limitation to the approach this library takes. `bs-json` tries to be as lightweight as possible while being JavaScript-compatible, and because it utilizes existing JavaScript APIs to do as much work as possible, it can only decode JSON as a subset of JavaScript. While JSON does not put a limit on the size of a number, JavaScript does, and that limit is therefore inherited by this library.

[Rex Json](https://redex.github.io/package/rex-json) might do, or with some tweaking be able to do what you want since it it's a self-contained implementation of both parsing and decoding.

Alternatively, if you're able to change the encoding, to a string for example, you could write a decoder that would allow you to work with numbers larger than what JavaScript allows. Otherwise it's unfortunately out of scope.

So I'll close this for that reason, but feel free to continue to discuss it, ask questions or suggest some other solution that might work for you.

**Closed by glennsl** 2018-06-06 15:59 UTC

**Comment by ChristophGr** [comment] 2018-06-06 16:20
I suspected as much, just wanted to make sure.
Thanks for the hint.
